spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

jwt:
  secret: dGVzdFNlY3JldEtleUZvclRlc3RpbmdQdXJwb3Nlc09ubHkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
  expiration: 86400000

logging:
  level:
    com.backend: WARN
    org.springframework: WARN
    org.hibernate: WARN
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
