spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5434/la_resistencia_db}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin123}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8081}

jwt:
  secret: ${JWT_SECRET:RGVmYXVsdFNlY3JldEtleU9ubHlGb3JEZXZQbGVhc2VDaGFuZ2VJblByb2R1Y3Rpb24=}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.backend: DEBUG
    org.springframework.security: INFO
    org.springframework.security.config.annotation.authentication.configuration: ERROR

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
